apiVersion: v1  #headless service
kind: Service
metadata:
  name: mysql-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP: {{ .Values.headless.clusterip }}
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306