apiVersion: v1  #headless service
kind: Service
metadata:
  name: mongo-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP:   {{ .Values.headlessservice.clusterip }} 
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017