apiVersion: v1  #headless service
kind: Service
metadata:
  name: redis-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP: {{ .Values.headless.clusterip }}
  selector:
    project: roboshop
    tier: db
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379