apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping   
    spec:
      containers:
        - name: shipping
          image: "{{ .Values.deployment.repository}}:{{ .Values.deployment.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "252Mi"
            limits:
              cpu: "150m"
              memory: "300Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            # tcpSocket:
            #   port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: shipping
      # affinity:
      #    nodeAffinity:
      #      requiredDuringSchedulingIgnoredDuringExecution:
      #        nodeSelectorTerms:
      #          - matchExpressions:
      #              - key: tier
      #                operator: In
      #                values:
      #                  - backend2