apiVersion: v1  #headless service
kind: Service
metadata:
  name: rabbitmq-headless-service
  namespace: roboshop
spec:
  # This makes the service "headless"
  clusterIP: {{ .Values.headlessservice.clusterip }} 
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672