apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: frontend 
spec:
  selector:
    project: roboshop
    tier: backend
    component: frontend 
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80